### ISSUE TITLE
Support for OpenAPI

### ISSUE THREAD

**Issue by judepereira** [storyscript/runtime#439]
There are two approaches to adding OpenAPI, one of which is easier, and fits into the system better:
## Approach 1 - Convert an OpenAPI spec into the OMG spec
**Pros:**
1. No changes to the frontends (Storyscript Hub and the LSP server for Storyscript) and runtime
2. Frontends, runtime, and everything else will never need to play catch-up, when a major version of OpenAPI is released.

**Cons:**
1. Two files will exist in the target repository (addition of microservice.yaml). However, since the microservice.yaml will be generated by a generator, this might not necessarily be a con.

For the purpose of "mapping" the OpenAPI spec to OMG, OpenAPI's `operationId ` field will be used as the action name in the OMG - everything else is directly mappable.

## Approach 2 - Link to an OpenAPI spec from the OMG spec
**Pros:**
1. No duplication of content (however, this may be ignored as a pro, since the microservice.yaml can be generated from the OpenAPI spec by a generator - approach 1).

**Cons:**
1. All frontends (such as the Storyscript Hub and the LSP server for Storyscript) will need to add support for rendering OpenAPI content.
2. Maintenance nightmare - whenever a major version of OpenAPI is released, the frontends (as described in point 1 above) will need to play catch-up.

**Comment by rohit121** [comment]
Minutes of the meeting over call-
Approach one is better to run a one time conversion from the open api spec to generate a microservice.yaml.. Reduces the changes we need to do in the language,HUB etc
OMG CLI can support a new method to facilitate this.
Operator Id to be used when available as the action, otherwise auto generate from the path mentioned.

Operation id definition from spec
https://swagger.io/docs/specification/basic-structure/
operationId	string	Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.

**Comment by wilzbach** [comment]
Strong vote for approach #1. Not looking forward at adding tons of different ways to do services in the compiler + LSP. A side benefit is that we need to make OMG powerful enough to be a map target.

BTW operationId is optional, so while this is a very good strategy, we should consider strategies to auto-generate them for a automatic support of existing openapi without any modifications required from the owner.

**Comment by judepereira** [comment]
@wilzbach yes, I will come up with something in the absence of `operationId`.

**Comment by judepereira** [comment]
Supported in master.
