### ISSUE TITLE
Slow while

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#532]
- [ ] only run one test
- [x] don't log every line
- [x] only sleep every 10000th time

**Comment by TonyRice** [comment]
I'll get on that!

**Comment by wilzbach** [comment]
@judepereira has already these changes on his local machine.

**Comment by TonyRice** [comment]
Okay coolPowered by Cricket Wireless
-------- Original message --------From: Sebastian Wilzbach <notifications@github.com> Date: 9/20/19  11:38 AM  (GMT-06:00) To: storyscript/runtime <runtime@noreply.github.com> Cc: Tony Rice <tony@tonyrice.me>, Comment <comment@noreply.github.com> Subject: Re: [storyscript/runtime] Slow while (#532) @judepereira has already these changes on his local machine.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/storyscript/runtime/issues/532?email_source=notifications\u0026email_token=AAJHX4FM2SABSHIMVRZ3BUTQKT373A5CNFSM4IYY4GXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7HH3JQ#issuecomment-533626278",
"url": "https://github.com/storyscript/runtime/issues/532?email_source=notifications\u0026email_token=AAJHX4FM2SABSHIMVRZ3BUTQKT373A5CNFSM4IYY4GXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7HH3JQ#issuecomment-533626278",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
Sent via Migadu.com, world's easiest email hosting

**Comment by judepereira** [comment]
Tony, Sebastian - on second thoughts, remove the while loop limit and sleep timeout. Enforce a 1 minute execution time in the asyncio task created to execute that story. This way, nobody can:
1. Run infinite while loops by calling a function which loops 99999 times
2. Monopolise the runtime when there are no other tasks

What do you guys think? 



Cheers,
Jude Pereira

**Comment by TonyRice** [comment]
> Tony, Sebastian - on second thoughts, remove the while loop limit and sleep timeout. Enforce a 1 minute execution time in the asyncio task created to execute that story. This way, nobody can: 1. Run infinite while loops by calling a function which loops 99999 times 2. Monopolise the runtime when there are no other tasks What do you guys think? Cheers, Jude Pereira
> […](#)
> Op 20 sep. 2019 om 18:14 heeft Sebastian Wilzbach ***@***.***> het volgende geschreven: ﻿ only run one test don't log every line only sleep every 10000th time — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I think the main problem with that, is a loop shouldn't be limited by time of execution due to the fact that some tasks could take a long time, but not necessarily take up a lot of resources.

For example, let's say a service takes over a minute to return a piece of data, or more specifically a microservice takes 10 seconds to return data, but we need to do it 15 times.

Maybe we can figure out some sort of way to detect if a loop is going to run infinitely, or maybe figure out if a function is going to return the same value, and simply cut down on execution time.

This is a tricky problem to solve, and ideally, the end goal is to ensure that a loop doesn't consume all the resources of the runtime.

**Comment by judepereira** [comment]
Hmm, that makes sense. Let’s stick to the prized changes by Sebastian then. 


Cheers,
Jude Pereira
